export { Header } from "./components/header/Header"
export { Layout } from "./components/layout/Layout"
export { LayoutSidebar } from "./components/layout/LayoutSidebar"
export { New } from "./components/hero/New"
export { Recommended } from "./components/hero/Recommended"
export { AlbumComp } from "./components/album/AlbumComp"
export { Playlists } from "./components/playlist/Playlists"
export { Artists } from "./components/artist/Artists"
export { LoginForm } from "./components/auth/LoginForm"
export { SignUpForm } from "./components/auth/SignUpForm"
export { SearchComp } from "./components/search/SearchComp"


// Page
export { Home } from "./pages/Home"
export { Albums } from "./pages/Albums"
export { Playlist } from "./pages/Playlist"
export { Artist } from "./pages/Artist"
export { Login } from "./pages/Login"
export { Search } from "./pages/Search"
export { Profile } from "./pages/Profile"
export { AlbumDetails } from "./pages/AlbumDetails"
export { SongDetails } from "./pages/SongDetails"
export { PlaylistDetails } from "./pages/PlaylistDetails"
