FROM node:alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM node:alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
COPY . ./
CMD [ "npm", "start" ]